version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A todo_project worker -l info
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
