from django.urls import path

from .api_views import (
    AnnouncementListCreateApi,
    AuthLoginApi,
    AuthLogoutApi,
    AuthSignupApi,
    DashboardApi,
    EventListCreateApi,
    HolidayListCreateApi,
    InvitationAcceptApi,
    InvitationCreateApi,
    LeaveApproveRejectCancelApi,
    LeaveBalanceMeApi,
    LeaveLedgerAdjustmentApi,
    LeaveRequestListCreateApi,
    LeaveTypeListCreateApi,
    MemberDeactivateApi,
    MemberDetailApi,
    MemberListApi,
    NotificationReadAllApi,
    NotificationReadApi,
    NotificationsListApi,
    OrganizationDetailApi,
    OrganizationListCreateApi,
    TaskAttachmentApi,
    TaskBlockApi,
    TaskCollaboratorsApi,
    TaskCommentsApi,
    TaskCompleteApi,
    TaskDetailApi,
    TaskListCreateApi,
    TaskReopenApi,
    TaskUnblockApi,
    TaskUpdatesApi,
    TeamDashboardApi,
    TeamDetailApi,
    TeamListCreateApi,
    TeamMembersApi,
)

urlpatterns = [
    path('auth/signup', AuthSignupApi.as_view()),
    path('auth/login', AuthLoginApi.as_view()),
    path('auth/logout', AuthLogoutApi.as_view()),
    path('organizations', OrganizationListCreateApi.as_view()),
    path('organizations/<int:org_id>', OrganizationDetailApi.as_view()),
    path('organizations/<int:org_id>/invitations', InvitationCreateApi.as_view()),
    path('invitations/<str:token>/accept', InvitationAcceptApi.as_view()),
    path('organizations/<int:org_id>/members', MemberListApi.as_view()),
    path('organizations/<int:org_id>/members/<int:member_id>', MemberDetailApi.as_view()),
    path('organizations/<int:org_id>/members/<int:member_id>/deactivate', MemberDeactivateApi.as_view()),
    path('organizations/<int:org_id>/teams', TeamListCreateApi.as_view()),
    path('organizations/<int:org_id>/teams/<int:team_id>', TeamDetailApi.as_view()),
    path('organizations/<int:org_id>/teams/<int:team_id>/members', TeamMembersApi.as_view()),
    path('organizations/<int:org_id>/teams/<int:team_id>/members/<int:member_id>', TeamMembersApi.as_view()),
    path('organizations/<int:org_id>/tasks', TaskListCreateApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>', TaskDetailApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>/updates', TaskUpdatesApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>/comments', TaskCommentsApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>/attachments', TaskAttachmentApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>/block', TaskBlockApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>/unblock', TaskUnblockApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>/complete', TaskCompleteApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>/reopen', TaskReopenApi.as_view()),
    path('organizations/<int:org_id>/tasks/<int:task_id>/collaborators', TaskCollaboratorsApi.as_view()),
    path('organizations/<int:org_id>/leave-types', LeaveTypeListCreateApi.as_view()),
    path('organizations/<int:org_id>/leave-balances/me', LeaveBalanceMeApi.as_view()),
    path('organizations/<int:org_id>/leave-requests', LeaveRequestListCreateApi.as_view()),
    path('organizations/<int:org_id>/leave-requests/<int:request_id>/approve', LeaveApproveRejectCancelApi.as_view(), {'action': 'approve'}),
    path('organizations/<int:org_id>/leave-requests/<int:request_id>/reject', LeaveApproveRejectCancelApi.as_view(), {'action': 'reject'}),
    path('organizations/<int:org_id>/leave-requests/<int:request_id>/cancel', LeaveApproveRejectCancelApi.as_view(), {'action': 'cancel'}),
    path('organizations/<int:org_id>/leave-ledger/adjustments', LeaveLedgerAdjustmentApi.as_view()),
    path('organizations/<int:org_id>/holidays', HolidayListCreateApi.as_view()),
    path('organizations/<int:org_id>/events', EventListCreateApi.as_view()),
    path('organizations/<int:org_id>/announcements', AnnouncementListCreateApi.as_view()),
    path('organizations/<int:org_id>/dashboard', DashboardApi.as_view()),
    path('organizations/<int:org_id>/teams/<int:team_id>/dashboard', TeamDashboardApi.as_view()),
    path('notifications', NotificationsListApi.as_view()),
    path('notifications/<int:notification_id>/read', NotificationReadApi.as_view()),
    path('notifications/read-all', NotificationReadAllApi.as_view()),
]
