# Generated by Django 5.2.10 on 2026-08-25 10:32

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def bootstrap_organizations(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Organization = apps.get_model('todo_app', 'Organization')
    Membership = apps.get_model('todo_app', 'Membership')
    Team = apps.get_model('todo_app', 'Team')
    Task = apps.get_model('todo_app', 'Task')
    LeaveType = apps.get_model('todo_app', 'LeaveType')
    LeaveLedgerEntry = apps.get_model('todo_app', 'LeaveLedgerEntry')

    def display_name_for(user):
        full_name = ' '.join(part for part in [user.first_name, user.last_name] if part).strip()
        return full_name or user.username

    for user in User.objects.all():
        if Membership.objects.filter(user=user).exists():
            membership = Membership.objects.filter(user=user).first()
            organization = membership.organization
        else:
            base_name = f'{user.username} Workspace'
            base_slug = slugify(base_name) or f'user-{user.pk}-workspace'
            slug = base_slug
            suffix = 1
            while Organization.objects.filter(slug=slug).exists():
                suffix += 1
                slug = f'{base_slug}-{suffix}'
            organization = Organization.objects.create(
                name=base_name,
                slug=slug,
                timezone='Asia/Kolkata',
                work_week='Mon-Fri',
                leave_year_start=django.utils.timezone.localdate(),
                created_by_id=user.id,
            )
            membership = Membership.objects.create(
                organization=organization,
                user_id=user.id,
                display_name=display_name_for(user),
                is_employee=True,
                is_manager=True,
                is_hr=True,
                is_owner=True,
                active=True,
            )
            team = Team.objects.create(
                organization=organization,
                name='General',
                manager=membership,
            )
            for leave_name, allocation, carry_forward, reason_required in [
                ('Casual leave', Decimal('12.0'), False, False),
                ('Sick leave', Decimal('10.0'), False, False),
                ('Earned/annual leave', Decimal('18.0'), True, False),
                ('Unpaid leave', Decimal('0.0'), False, True),
            ]:
                leave_type = LeaveType.objects.create(
                    organization=organization,
                    name=leave_name,
                    annual_allocation=allocation,
                    allow_carry_forward=carry_forward,
                    reason_required=reason_required,
                    unit='days',
                )
                if allocation:
                    LeaveLedgerEntry.objects.create(
                        organization=organization,
                        membership=membership,
                        leave_type=leave_type,
                        entry_type='allocation',
                        days=allocation,
                        note='Initial allocation',
                        created_by=membership,
                    )

    for task in Task.objects.all().order_by('id'):
        membership, _created = Membership.objects.get_or_create(
            user_id=task.primary_assignee_id,
            organization=Membership.objects.filter(user_id=task.user_id).first().organization,
            defaults={
                'display_name': display_name_for(User.objects.get(pk=task.primary_assignee_id)),
                'is_employee': True,
            },
        )
        team = Team.objects.filter(organization=membership.organization).first()
        if not team:
            team = Team.objects.create(organization=membership.organization, name='General', manager=membership)
        task.organization = membership.organization
        task.team = team
        task.primary_membership = membership
        task.task_key = task.task_key or f'ORG-{task.id:04d}'
        task.save(update_fields=['organization', 'team', 'primary_membership', 'task_key'])
        collaborator_ids = list(task.collaborators.values_list('id', flat=True))
        memberships = []
        for collaborator_id in collaborator_ids:
            collaborator_user = User.objects.get(pk=collaborator_id)
            collaborator_membership, _created = Membership.objects.get_or_create(
                organization=membership.organization,
                user_id=collaborator_id,
                defaults={
                    'display_name': display_name_for(collaborator_user),
                    'is_employee': True,
                },
            )
            memberships.append(collaborator_membership.id)
        if memberships:
            task.collaborator_memberships.set(memberships)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_officedairy_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'due_date', '-updated_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_from_stage',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_type',
            field=models.CharField(blank=True, choices=[('', 'No blocker'), ('dependency', 'Dependency'), ('review', 'Review'), ('access', 'Access'), ('clarification', 'Clarification'), ('bug', 'Bug'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_next_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_stage',
            field=models.CharField(blank=True, choices=[('', 'No checkpoint'), ('development', 'Development'), ('dev_deployment_pending', 'Dev Deployment Pending'), ('qa_testing_pending', 'QA Testing Pending'), ('production_deployment_pending', 'Production Deployment Pending'), ('production_testing_pending', 'Production Testing Pending'), ('ready_to_close', 'Ready to Close')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='from_progress_stage',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='to_progress_stage',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('is_employee', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_hr', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='todo_app.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'user__username'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='collaborator_memberships',
            field=models.ManyToManyField(blank=True, related_name='collaborative_task_memberships', to='todo_app.membership'),
        ),
        migrations.AddField(
            model_name='task',
            name='primary_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='todo_app.membership'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('invitation', 'Invitation'), ('task', 'Task'), ('leave', 'Leave'), ('event', 'Event'), ('announcement', 'Announcement'), ('admin', 'Administrative')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='todo_app.membership')),
            ],
            options={
                'ordering': ['is_read', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('work_week', models.CharField(default='Mon-Fri', max_length=32)),
                ('leave_year_start', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='todo_app.organization'),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('annual_allocation', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('allow_carry_forward', models.BooleanField(default=False)),
                ('reason_required', models.BooleanField(default=False)),
                ('unit', models.CharField(default='days', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='todo_app.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approver_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='todo_app.leavetype')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='todo_app.membership')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='todo_app.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='todo_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('allocation', 'Allocation'), ('carry_forward', 'Carry Forward'), ('approved_leave', 'Approved Leave'), ('cancellation_reversal', 'Cancellation Reversal'), ('hr_correction', 'HR Correction')], max_length=30)),
                ('days', models.DecimalField(decimal_places=1, max_digits=6)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='todo_app.leaverequest')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='todo_app.leavetype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_ledger_entries', to='todo_app.membership')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_ledger_entries', to='todo_app.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_ledger_entries', to='todo_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='todo_app.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='todo_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo_app.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('organization', 'task_key')},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to='todo_app.membership')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='todo_app.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='todo_app.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invited_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR'), ('owner', 'Owner')], default='employee', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='todo_app.membership')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_invitations', to='todo_app.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='todo_app.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='todo_app.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('celebration', 'Celebration'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('location_or_link', models.CharField(blank=True, max_length=255)),
                ('audience', models.CharField(choices=[('org', 'Entire organization'), ('teams', 'Specific teams')], default='org', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='todo_app.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='todo_app.organization')),
                ('teams', models.ManyToManyField(blank=True, related_name='events', to='todo_app.team')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('audience', models.CharField(choices=[('org', 'Entire organization'), ('teams', 'Specific teams')], default='org', max_length=20)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to='todo_app.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='todo_app.organization')),
                ('teams', models.ManyToManyField(blank=True, related_name='announcements', to='todo_app.team')),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='todo_app.team'),
        ),
        migrations.RunPython(bootstrap_organizations, noop),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('organization', 'user')},
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='todo_app.organization')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('organization', 'name', 'date')},
            },
        ),
    ]
